verbose = true

[tracers]
ntracers = 1
eps = 0.04
noise_amplitude = 0.0
# kmin set to (2\pi / Vˆ{1/3)
kmin_value = 0.0004
kmax_value = 0.15
# Volume factor corresponding to comoving volume up to redshift 20 in units of (1440 Mpc)ˆ3
V1440_factor = 1555
# nbar corresponding to 5 \times 10ˆ5 sources detected by ET during a 5-year mission
nbar_value = 1e-6

[bias]
b1set = [5]
b2set = [0.2]
bG2set = [0.1]
bGamma3set = [0.1]
bNabla2set = [0.1]
cct_2_0_set = [0.1]
cct_2_2_set = []
cct_2_4_set = []
cct_4_4_set = []
cct_4_6_set = []
use_universality_relation = true
universality_relation_p = 1

[cosmology]
omega_cdm_fid = 0.12
h_fid = 0.67
As_fid = 2.1
f_NL_fid = 50
includeAs = false

[power_spectrum]
nonlin = false
nocross_stoch = false
RSD = false
multipoles = [true, true, true]
active_bias = [true, true, true, true, true, true, true, true, true, true]
active_stoch = [true, true, true]
redshift = 0

[caching]
open_precomputed_files = true
save_precomputed_files = false

[plotting]
verbose = false
